import { StyleSheet } from 'react-native';
import { TOKENS } from '../constants/tokens';

export const appStyles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: TOKENS.background,
  },
  screenBase: {
    flex: 1,
    backgroundColor: TOKENS.background,
  },
  scrollBase: {
    flex: 1,
  },
  safeHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(252,249,248,0.94)',
  },
  topBar: {
    height: 60,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  avatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: TOKENS.surfaceHighest,
  },
  topBarTitle: {
    color: TOKENS.onBackground,
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  settingsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: TOKENS.surfaceLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsButtonText: {
    color: TOKENS.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  contentPadding: {
    paddingHorizontal: 20,
    gap: 16,
  },
  balanceCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 16,
    padding: 20,
    shadowColor: '#1c1b1b',
    shadowOpacity: 0.05,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  overline: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 11,
    letterSpacing: 1.8,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
    marginTop: 6,
  },
  balanceCurrency: {
    color: TOKENS.primaryContainer,
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  balanceAmount: {
    color: TOKENS.primaryContainer,
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: -1.2,
  },
  growthLabel: {
    marginTop: 12,
    color: TOKENS.primary,
    fontWeight: '700',
    fontSize: 12,
    letterSpacing: 0.4,
  },
  sectionHeaderRow: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  sectionTitle: {
    color: TOKENS.onBackground,
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -0.9,
  },
  sectionMeta: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 11,
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 1.3,
  },
  overviewBlock: {
    gap: 12,
  },
  donutPanel: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 16,
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#1c1b1b',
    shadowOpacity: 0.05,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 10 },
    elevation: 2,
  },
  donutOuter: {
    width: 166,
    height: 166,
    borderRadius: 83,
    borderWidth: 12,
    borderColor: TOKENS.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutInner: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: TOKENS.surfaceLowest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutValue: {
    fontSize: 32,
    fontWeight: '800',
    color: TOKENS.onBackground,
    letterSpacing: -0.7,
  },
  donutCaption: {
    marginTop: 2,
    fontSize: 9,
    letterSpacing: 1,
    color: TOKENS.onSurfaceVariant,
    fontWeight: '700',
  },
  progressList: {
    gap: 10,
  },
  progressRow: {
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLow,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 7,
  },
  progressLabel: {
    color: TOKENS.primary,
    fontSize: 11,
    letterSpacing: 1.6,
    fontWeight: '700',
  },
  progressAmount: {
    color: TOKENS.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  progressTrack: {
    width: '100%',
    height: 5,
    borderRadius: 999,
    backgroundColor: TOKENS.surfaceHigh,
    overflow: 'hidden',
  },
  progressTrackThick: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: TOKENS.surfaceHigh,
    overflow: 'hidden',
    marginTop: 14,
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  budgetHeroProgressFill: {
    width: '68%',
    backgroundColor: TOKENS.primaryContainer,
  },
  transactionItem: {
    borderRadius: 16,
    backgroundColor: TOKENS.surfaceLowest,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: '#1c1b1b',
    shadowOpacity: 0.03,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 1,
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  iconCircle: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    color: TOKENS.primary,
    fontWeight: '700',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  transactionName: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '600',
  },
  transactionDate: {
    marginTop: 2,
    color: TOKENS.onSurfaceVariant,
    fontSize: 11,
  },
  transactionAmount: {
    color: TOKENS.onBackground,
    fontSize: 16,
    fontWeight: '700',
  },
  heroAmount: {
    color: TOKENS.onBackground,
    fontSize: 46,
    fontWeight: '800',
    letterSpacing: -1.2,
    marginTop: 8,
  },
  dualCards: {
    flexDirection: 'row',
    gap: 10,
  },
  statCardPrimary: {
    flex: 1,
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 16,
    padding: 14,
    gap: 4,
  },
  statCardMuted: {
    flex: 1,
    backgroundColor: TOKENS.surfaceLow,
    borderRadius: 16,
    padding: 14,
    gap: 4,
  },
  statCardValue: {
    color: TOKENS.onBackground,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.7,
  },
  chartCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingTop: 18,
    paddingBottom: 12,
    minHeight: 210,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  chartColumnWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  chartColumn: {
    width: '100%',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    minHeight: 24,
  },
  chartLabel: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1,
  },
  chartLabelActive: {
    color: TOKENS.primary,
    fontWeight: '800',
  },
  categoryCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 16,
    padding: 14,
    gap: 10,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryName: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '600',
  },
  categoryPercent: {
    marginTop: 2,
    color: TOKENS.onSurfaceVariant,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  categoryAmount: {
    color: TOKENS.onBackground,
    fontSize: 18,
    fontWeight: '700',
  },
  insightCard: {
    marginTop: 4,
    borderRadius: 16,
    padding: 18,
    backgroundColor: TOKENS.primaryContainer,
  },
  insightOverline: {
    color: 'rgba(0,80,39,0.75)',
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: '700',
  },
  insightTitle: {
    marginTop: 8,
    color: '#005027',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    letterSpacing: -0.4,
  },
  insightButton: {
    marginTop: 14,
    alignSelf: 'flex-start',
    borderRadius: 10,
    backgroundColor: TOKENS.surfaceLowest,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  insightButtonText: {
    color: '#005027',
    fontSize: 10,
    letterSpacing: 1.8,
    fontWeight: '800',
  },
  heroTitle: {
    color: TOKENS.onBackground,
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: -1.3,
  },
  budgetHeroCard: {
    marginTop: 4,
    borderRadius: 16,
    backgroundColor: TOKENS.surfaceLowest,
    padding: 18,
  },
  budgetTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  budgetTopRight: {
    alignItems: 'flex-end',
  },
  budgetSpent: {
    marginTop: 4,
    color: TOKENS.onBackground,
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: -1,
  },
  budgetLimit: {
    marginTop: 4,
    color: TOKENS.onBackground,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaText: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 11,
    fontWeight: '500',
  },
  budgetRowCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 16,
    padding: 14,
    gap: 8,
  },
  budgetRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  budgetCategory: {
    color: TOKENS.onBackground,
    fontSize: 16,
    fontWeight: '600',
  },
  budgetRatio: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '700',
  },
  glassCard: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: TOKENS.primary,
    gap: 10,
  },
  glassTitle: {
    color: TOKENS.onPrimary,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  glassBody: {
    color: '#b6f5ce',
    fontSize: 13,
    lineHeight: 20,
  },
  glassLink: {
    color: TOKENS.onPrimary,
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: '700',
  },
  subPageHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    paddingHorizontal: 20,
    backgroundColor: 'rgba(252,249,248,0.94)',
  },
  subPageHeaderInner: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  closeButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: TOKENS.surfaceLow,
  },
  closeButtonText: {
    color: TOKENS.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  helpText: {
    color: TOKENS.muted,
    fontSize: 18,
    fontWeight: '500',
  },
  centerAmount: {
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  amountInputValue: {
    color: TOKENS.primary,
    fontSize: 52,
    fontWeight: '800',
    letterSpacing: -1.7,
  },
  categoryChipGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 6,
    rowGap: 10,
  },
  categoryChipWrap: {
    alignItems: 'center',
    gap: 8,
    width: '24%',
  },
  categoryChip: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: TOKENS.surfaceHighest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryChipActive: {
    backgroundColor: TOKENS.primaryContainer,
  },
  categoryChipText: {
    color: TOKENS.onBackground,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  categoryChipTextActive: {
    color: '#005027',
  },
  categoryChipLabel: {
    color: TOKENS.onBackground,
    fontSize: 11,
    fontWeight: '600',
  },
  categoryChipLabelMuted: {
    opacity: 0.5,
  },
  formGroup: {
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLow,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 10,
    gap: 4,
  },
  flatInput: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '500',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  keypadShell: {
    marginTop: 12,
    marginHorizontal: -20,
    paddingTop: 20,
    paddingHorizontal: 22,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    backgroundColor: TOKENS.surfaceLow,
    gap: 10,
  },
  keypadGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 6,
  },
  keyButton: {
    width: '33%',
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
  },
  keyText: {
    color: TOKENS.onBackground,
    fontSize: 30,
    fontWeight: '700',
    letterSpacing: -0.8,
  },
  addButton: {
    marginTop: 6,
    height: 60,
    borderRadius: 14,
    backgroundColor: TOKENS.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#005027',
    fontSize: 16,
    letterSpacing: 1.3,
    fontWeight: '800',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(252,249,248,0.88)',
    paddingTop: 10,
    borderTopWidth: 0,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    gap: 4,
  },
  navGlyph: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceHighest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navGlyphActive: {
    backgroundColor: 'rgba(46,204,113,0.2)',
  },
  navGlyphText: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: '700',
  },
  navGlyphTextActive: {
    color: TOKENS.primary,
  },
  navLabel: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 10,
    letterSpacing: 1,
    fontWeight: '600',
  },
  navLabelActive: {
    color: TOKENS.primary,
    fontWeight: '700',
  },
  fab: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: TOKENS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -24,
  },
  fabText: {
    color: TOKENS.onPrimary,
    fontSize: 30,
    marginTop: -1,
    lineHeight: 34,
    fontWeight: '400',
  },
  loginRoot: {
    flex: 1,
    backgroundColor: TOKENS.background,
    paddingHorizontal: 24,
  },
  loginTopSpace: {
    paddingTop: 56,
  },
  logoRow: {
    alignItems: 'center',
    gap: 8,
  },
  logoMark: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: TOKENS.surfaceLowest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoMarkText: {
    fontSize: 22,
    fontWeight: '800',
    color: TOKENS.primary,
  },
  loginTitle: {
    marginTop: 8,
    fontSize: 34,
    fontWeight: '900',
    letterSpacing: -1.3,
    color: TOKENS.onBackground,
  },
  loginSubtitle: {
    marginTop: 6,
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1.8,
    color: TOKENS.onSurfaceVariant,
    fontWeight: '600',
  },
  loginForm: {
    marginTop: 42,
    gap: 14,
  },
  loginField: {
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLow,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  loginLabel: {
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    color: TOKENS.onSurfaceVariant,
    fontWeight: '700',
  },
  loginInput: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '500',
    padding: 0,
  },
  loginPrimaryButton: {
    marginTop: 8,
    height: 56,
    borderRadius: 14,
    backgroundColor: TOKENS.primaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginPrimaryButtonText: {
    color: '#005027',
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  loginHelperRow: {
    marginTop: 18,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  loginHelperText: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 13,
  },
  loginHelperAction: {
    color: TOKENS.primary,
    fontSize: 13,
    fontWeight: '700',
  },
  loginSocialRow: {
    marginTop: 34,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 14,
  },
  socialButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: TOKENS.surfaceHighest,
  },
  socialButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: TOKENS.onBackground,
  },
});
