import { StyleSheet } from 'react-native';
import { TOKENS } from '../constants/tokens';

export const appStyles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: TOKENS.background,
  },
  screenBase: {
    flex: 1,
    backgroundColor: TOKENS.background,
  },
  scrollBase: {
    flex: 1,
  },
  safeHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 20,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255,255,255,0.9)',
  },
  topBar: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  avatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: TOKENS.surfaceHighest,
  },
  topBarTitle: {
    color: TOKENS.onBackground,
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  settingsButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: TOKENS.surfaceLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsButtonText: {
    color: TOKENS.primary,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1,
  },
  contentPadding: {
    paddingHorizontal: 18,
    gap: 18,
  },
  balanceCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 14,
    padding: 22,
    borderBottomWidth: 2,
    borderBottomColor: TOKENS.primary,
  },
  overline: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 10,
    letterSpacing: 2.1,
    fontWeight: '600',
  },
  balanceRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
    marginTop: 6,
  },
  balanceCurrency: {
    color: TOKENS.primary,
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -1,
  },
  balanceAmount: {
    color: TOKENS.primary,
    fontSize: 44,
    fontWeight: '800',
    letterSpacing: -1.4,
  },
  growthLabel: {
    marginTop: 10,
    color: TOKENS.primary,
    fontWeight: '700',
    fontSize: 12,
  },
  sectionHeaderRow: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  sectionTitle: {
    color: TOKENS.primary,
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: -0.8,
  },
  sectionMeta: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 12,
    fontWeight: '500',
  },
  overviewBlock: {
    gap: 12,
  },
  donutPanel: {
    backgroundColor: TOKENS.surfaceLow,
    borderRadius: 14,
    paddingVertical: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutOuter: {
    width: 166,
    height: 166,
    borderRadius: 90,
    borderWidth: 14,
    borderColor: TOKENS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutInner: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: TOKENS.surfaceLowest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutValue: {
    fontSize: 30,
    fontWeight: '800',
    color: TOKENS.primary,
    letterSpacing: -0.7,
  },
  donutCaption: {
    marginTop: 2,
    fontSize: 9,
    letterSpacing: 1,
    color: TOKENS.onSurfaceVariant,
    fontWeight: '700',
  },
  progressList: {
    gap: 10,
  },
  progressRow: {
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLow,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 7,
  },
  progressLabel: {
    color: TOKENS.primary,
    fontSize: 11,
    letterSpacing: 1.6,
    fontWeight: '700',
  },
  progressAmount: {
    color: TOKENS.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  progressTrack: {
    width: '100%',
    height: 6,
    borderRadius: 999,
    backgroundColor: TOKENS.surfaceHighest,
    overflow: 'hidden',
  },
  progressTrackThick: {
    width: '100%',
    height: 8,
    borderRadius: 999,
    backgroundColor: TOKENS.surfaceHighest,
    overflow: 'hidden',
    marginTop: 14,
    marginBottom: 8,
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
  },
  transactionItem: {
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLowest,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  transactionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  iconCircle: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: TOKENS.surfaceLow,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconText: {
    color: TOKENS.primary,
    fontWeight: '700',
    fontSize: 11,
    letterSpacing: 0.5,
  },
  transactionName: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '600',
  },
  transactionDate: {
    marginTop: 2,
    color: TOKENS.onSurfaceVariant,
    fontSize: 11,
  },
  transactionAmount: {
    color: TOKENS.primary,
    fontSize: 16,
    fontWeight: '700',
  },
  heroAmount: {
    color: TOKENS.primary,
    fontSize: 46,
    fontWeight: '800',
    letterSpacing: -1.2,
    marginTop: 8,
  },
  dualCards: {
    flexDirection: 'row',
    gap: 10,
  },
  statCardPrimary: {
    flex: 1,
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 14,
    padding: 14,
    borderBottomWidth: 2,
    borderBottomColor: TOKENS.primary,
    gap: 4,
  },
  statCardMuted: {
    flex: 1,
    backgroundColor: TOKENS.surfaceLow,
    borderRadius: 14,
    padding: 14,
    gap: 4,
  },
  statCardValue: {
    color: TOKENS.primary,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.7,
  },
  chartCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingTop: 18,
    paddingBottom: 12,
    minHeight: 210,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
  },
  chartColumnWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  chartColumn: {
    width: '100%',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    minHeight: 24,
  },
  chartLabel: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1,
  },
  chartLabelActive: {
    color: TOKENS.primary,
    fontWeight: '800',
  },
  categoryCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 14,
    padding: 14,
    gap: 10,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  categoryName: {
    color: TOKENS.onBackground,
    fontSize: 15,
    fontWeight: '600',
  },
  categoryPercent: {
    marginTop: 2,
    color: TOKENS.onSurfaceVariant,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  categoryAmount: {
    color: TOKENS.primary,
    fontSize: 18,
    fontWeight: '700',
  },
  insightCard: {
    marginTop: 4,
    borderRadius: 14,
    padding: 18,
    backgroundColor: TOKENS.primary,
  },
  insightOverline: {
    color: 'rgba(255,255,255,0.65)',
    fontSize: 10,
    letterSpacing: 2,
    fontWeight: '700',
  },
  insightTitle: {
    marginTop: 8,
    color: '#ffffff',
    fontSize: 20,
    lineHeight: 28,
    fontWeight: '700',
    letterSpacing: -0.4,
  },
  insightButton: {
    marginTop: 14,
    alignSelf: 'flex-start',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  insightButtonText: {
    color: TOKENS.primary,
    fontSize: 10,
    letterSpacing: 1.8,
    fontWeight: '800',
  },
  heroTitle: {
    color: TOKENS.primary,
    fontSize: 48,
    fontWeight: '800',
    letterSpacing: -1.3,
  },
  budgetHeroCard: {
    marginTop: 4,
    borderRadius: 14,
    backgroundColor: TOKENS.surfaceLowest,
    padding: 18,
  },
  budgetTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  budgetSpent: {
    marginTop: 4,
    color: TOKENS.primary,
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: -1,
  },
  budgetLimit: {
    marginTop: 4,
    color: TOKENS.primary,
    fontSize: 24,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  rowBetween: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  metaText: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 11,
    fontWeight: '500',
  },
  budgetRowCard: {
    backgroundColor: TOKENS.surfaceLowest,
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  budgetRowHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  budgetCategory: {
    color: TOKENS.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  budgetRatio: {
    color: TOKENS.primary,
    fontSize: 15,
    fontWeight: '700',
  },
  glassCard: {
    borderRadius: 14,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
    gap: 10,
  },
  glassTitle: {
    color: TOKENS.primary,
    fontSize: 22,
    fontWeight: '700',
    letterSpacing: -0.5,
  },
  glassBody: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 13,
    lineHeight: 20,
  },
  glassLink: {
    color: TOKENS.primary,
    fontSize: 11,
    letterSpacing: 1.5,
    fontWeight: '700',
  },
  subPageHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 30,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255,255,255,0.92)',
  },
  subPageHeaderInner: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  closeButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: TOKENS.surfaceLow,
  },
  closeButtonText: {
    color: TOKENS.primary,
    fontSize: 12,
    fontWeight: '800',
  },
  helpText: {
    color: TOKENS.muted,
    fontSize: 20,
    fontWeight: '500',
  },
  centerAmount: {
    alignItems: 'center',
    gap: 8,
    marginBottom: 10,
  },
  amountInputValue: {
    color: TOKENS.primary,
    fontSize: 56,
    fontWeight: '800',
    letterSpacing: -1.7,
  },
  categoryChipGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  categoryChipWrap: {
    alignItems: 'center',
    gap: 8,
  },
  categoryChip: {
    width: 54,
    height: 54,
    borderRadius: 10,
    backgroundColor: TOKENS.surfaceHighest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryChipActive: {
    backgroundColor: TOKENS.primary,
  },
  categoryChipText: {
    color: TOKENS.primary,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  categoryChipTextActive: {
    color: TOKENS.onPrimary,
  },
  categoryChipLabel: {
    color: TOKENS.primary,
    fontSize: 11,
    fontWeight: '600',
  },
  formGroup: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(119,119,119,0.25)',
    paddingBottom: 6,
    marginBottom: 10,
    gap: 4,
  },
  flatInput: {
    color: TOKENS.onBackground,
    fontSize: 16,
    fontWeight: '500',
    paddingHorizontal: 0,
    paddingVertical: 2,
  },
  keypadShell: {
    marginTop: 12,
    marginHorizontal: -18,
    paddingTop: 20,
    paddingHorizontal: 22,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: TOKENS.surfaceLow,
    gap: 10,
  },
  keypadGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 6,
  },
  keyButton: {
    width: '33%',
    height: 56,
    alignItems: 'center',
    justifyContent: 'center',
  },
  keyText: {
    color: TOKENS.primary,
    fontSize: 33,
    fontWeight: '700',
    letterSpacing: -0.8,
  },
  addButton: {
    marginTop: 6,
    height: 58,
    borderRadius: 12,
    backgroundColor: TOKENS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: TOKENS.onPrimary,
    fontSize: 16,
    letterSpacing: 1.3,
    fontWeight: '700',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(255,255,255,0.95)',
    paddingTop: 10,
    borderTopWidth: 0,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 64,
    gap: 4,
  },
  navGlyph: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: TOKENS.surfaceHighest,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navGlyphActive: {
    backgroundColor: TOKENS.primary,
  },
  navGlyphText: {
    color: TOKENS.primary,
    fontSize: 10,
    fontWeight: '700',
  },
  navGlyphTextActive: {
    color: TOKENS.onPrimary,
  },
  navLabel: {
    color: TOKENS.onSurfaceVariant,
    fontSize: 9,
    letterSpacing: 1,
    fontWeight: '600',
  },
  navLabelActive: {
    color: TOKENS.primary,
    fontWeight: '700',
  },
  fab: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: TOKENS.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -22,
  },
  fabText: {
    color: TOKENS.onPrimary,
    fontSize: 32,
    marginTop: -1,
    lineHeight: 34,
    fontWeight: '400',
  },
});
